# Generated by Django 3.0.3 on 2020-03-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0002_auto_20200325_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('confirmed', models.IntegerField()),
                ('active', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('death', models.IntegerField()),
                ('source', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
